# Generated by Django 5.2.5 on 2025-08-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="demo_video",
            field=models.FileField(blank=True, null=True, upload_to="products/videos/"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_code_product",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="source_file",
            field=models.FileField(blank=True, null=True, upload_to="products/source/"),
        ),
    ]
